### PR TITLE
Support Honeywell PDAs

### PR DESCRIPTION
**Pull request by aguilaair**
This version should support Honeywell PDAs that are compatible with https://pub.dev/packages/honeywell_scanner

Thanks to @pedropastor for the marvelous idea.

I will not merge until I have had the chance to try it on a PDA I have bought, which will hopefully arrive soon. However, I would love for other people to test and confirm this implementation works on their Honeywell-powered PDAs

### CODE REVIEW

**Comment by aguilaair** [comment]
Confirmed to still work on Android and web devices

**Comment by aguilaair** [comment]
Screenshot_20211231-173352
Screenshot_20211231-173418

**Comment by pedropastor** [comment]
Oh well I was performing some testing but I see you just went straight ahead haha.
I have tested my reduced version of the app with no camera successfully.

In the following days I will give a try to your branch with my PDA and confirm the results

**Comment by aguilaair** [comment]
Happy new year, @pedropastor!
hahaha yeah had some spare time and went right ahead 🤣 
Let me know how it works!

**Comment by pedropastor** [comment]
Hi @aguilaair, I made some testing on EDA51 device. It works smooth. No problems found pausing, switching between apps, screen on and off... so it seems it got all covered.

Just one point, related to design / UI. On first screen it is not pretty clear the app is working in PDA mode. The legend is small and says PDA scan available which I think it is a bit misleading, available is not "active".

Maybe adding a graph like four squares with a legend fits better, like this:

```
|--------------------|
.      PDA MODE    .
|___________________ |
```

I leave that up to you ;) 

Edit (obviously github formats dashes so the example image was crap, trying to fix it)

Edit2: I am not in the mood of fighting github today, I hope you get the point, if not, I will hand draw it and attach it

Edit 3 by @aguilaair: fixed it :)

**Comment by aguilaair** [comment]
For sure, I'll try to make it a bit clearer and maybe even default to the PDA active mode, which is likely why you have a Honeywell device, thanks for your feedback, I really appreciate it.

If you could test with the latest build which has a bunch of improvements incl. settings screen and web cert updated and check that it still works I'd appreciate it as I have also added support for any PDA with an invisible text field, and I wanna make sure there are no conflicts. Here is the apk: https://codemagic.io/apps/61ae30a600c5fee93a2b32db/61af835df16a5919d7c363fc/latest_build (working on the #11  PR)

Thanks again for all your help

**Comment by pedropastor** [comment]
Sure I will give it a try.
I am in the middle of a big deployment, will try to find gaps in between our system guys uploading versions, so give me a couple of days, so far I will get it done this weekend

**Comment by aguilaair** [comment]
Of course, no worries!

**Comment by aguilaair** [comment]
imagen
Something like this, @pedropastor?

The button doesn't appear because it is running on the desktop app, but the button would be below the card

**Pull request merged**
